#tomcat的配置
server:
  port: 808
  error:
    path: /error
  servlet:
    session:
      timeout: 30m
    context-path: /mvc
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500

#模版thymeleaf配置
spring:
  thymeleaf:
    #路径
    prefix: classpath:/public/
    #后缀
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    cache: false
 